#!/usr/bin/env python3
"""
Stock Image Fetcher for LexiCore

Fetches commercial-use legal-themed stock images from Pexels API and
generates a TypeScript manifest for the React/Next.js app.

Usage:
    export PEXELS_API_KEY="your_api_key"
    python scripts/fetch_images.py

Requirements:
    pip install requests
"""

import os
import sys
import time
from pathlib import Path
from typing import Dict, List

try:
    import requests
except ImportError:
    print("Error: requests library not found.")
    print("Install with: pip install requests")
    sys.exit(1)

# Configuration
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")
if not PEXELS_API_KEY:
    print("Error: PEXELS_API_KEY environment variable not set.")
    print("Get an API key from: https://www.pexels.com/api/")
    sys.exit(1)

BASE_URL = "https://api.pexels.com/v1/search"

# Image categories for legal tech app
IMAGE_CATEGORIES = {
    "hero": {
        "query": "modern city skyline law justice professional",
        "orientation": "landscape",
        "count": 4,
        "subdir": "hero",
    },
    "carousel": {
        "query": "diverse people meeting office collaboration",
        "orientation": "landscape",
        "count": 6,
        "subdir": "carousel",
    },
    "cards": {
        "query": "documents contract paperwork desk legal office",
        "orientation": "landscape",
        "count": 12,
        "subdir": "cards",
    },
    "backgrounds": {
        "query": "dark abstract modern technology gradient",
        "orientation": "landscape",
        "count": 4,
        "subdir": "backgrounds",
    },
}

# Paths
PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = PROJECT_ROOT / "public" / "stock"
MANIFEST_PATH = PROJECT_ROOT / "src" / "config" / "imageManifest.ts"


def pexels_search(query: str, orientation: str, per_page: int) -> List[Dict]:
    """Search Pexels API for images."""
    headers = {"Authorization": PEXELS_API_KEY}
    params = {
        "query": query,
        "orientation": orientation,
        "per_page": per_page,
        "size": "large",
    }

    try:
        resp = requests.get(BASE_URL, headers=headers, params=params, timeout=20)
        resp.raise_for_status()
        data = resp.json()
        return data.get("photos", [])
    except requests.exceptions.RequestException as e:
        print(f"Error searching Pexels: {e}")
        return []


def download_image(url: str, dest_path: Path) -> bool:
    """Download image from URL to destination path."""
    try:
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()

        with dest_path.open("wb") as f:
            f.write(resp.content)

        return True
    except requests.exceptions.RequestException as e:
        print(f"Error downloading {url}: {e}")
        return False


def fetch_category(name: str, config: Dict) -> List[str]:
    """Fetch images for a category."""
    query = config["query"]
    orientation = config["orientation"]
    count = config["count"]
    subdir = config["subdir"]

    print(f"\n📸 Fetching {count} images for '{name}'")
    print(f"   Query: {query}")

    photos = pexels_search(query, orientation, count)
    if not photos:
        print(f"   ⚠️  No photos returned for {name}")
        return []

    saved_files = []
    for idx, photo in enumerate(photos[:count], start=1):
        # Choose best quality source
        src = photo.get("src", {})
        url = src.get("large") or src.get("medium") or src.get("original")

        if not url:
            print(f"   ⚠️  No URL found for photo {idx}")
            continue

        filename = f"{name}_{idx:02d}.jpg"
        dest = OUTPUT_ROOT / subdir / filename

        print(f"   [{idx}/{count}] Downloading {filename}...", end=" ")

        if download_image(url, dest):
            # Store relative path from public directory
            relative_path = f"/stock/{subdir}/{filename}"
            saved_files.append(relative_path)
            print("✅")
        else:
            print("❌")

        # Be polite to API
        time.sleep(0.3)

    return saved_files


def generate_manifest(manifest: Dict[str, List[str]]) -> None:
    """Generate TypeScript manifest file."""
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by scripts/fetch_images.py",
        "// Do not edit manually",
        "",
        "export const imageManifest = {",
    ]

    for category, files in manifest.items():
        if not files:
            lines.append(f"  {category}: [],")
            continue

        files_str = ",\n    ".join([f'"{path}"' for path in files])
        lines.append(f"  {category}: [")
        lines.append(f"    {files_str}")
        lines.append("  ],")

    lines.append("} as const;")
    lines.append("")
    lines.append("export type ImageCategory = keyof typeof imageManifest;")
    lines.append("")

    content = "\n".join(lines)
    MANIFEST_PATH.write_text(content, encoding="utf-8")

    print(f"\n📝 Manifest written to: {MANIFEST_PATH}")


def main():
    """Main execution."""
    print("=" * 60)
    print("  LexiCore Stock Image Fetcher")
    print("=" * 60)

    manifest = {}

    for name, config in IMAGE_CATEGORIES.items():
        files = fetch_category(name, config)
        manifest[name] = files

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)

    total_images = 0
    for category, files in manifest.items():
        count = len(files)
        total_images += count
        status = "✅" if count > 0 else "⚠️"
        print(f"  {status} {category}: {count} images")

    print(f"\n  Total: {total_images} images downloaded")

    generate_manifest(manifest)

    print("\n✅ Done!")
    print("\nNext steps:")
    print("  1. Review images in public/stock/")
    print("  2. Import imageManifest in your components:")
    print("     import { imageManifest } from '@/config/imageManifest';")
    print("  3. Use in components:")
    print("     <img src={imageManifest.hero[0]} alt='Hero' />")


if __name__ == "__main__":
    main()
